# Generated by Django 5.1.1 on 2024-12-01 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_category_productpurchase_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 20, 34, 39, 247110, tzinfo=datetime.timezone.utc)),
        ),
    ]
