# Generated by Django 5.1.1 on 2024-12-04 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_productpurchase_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 4, 17, 15, 5, 909640, tzinfo=datetime.timezone.utc)),
        ),
    ]
