# Generated by Django 5.1.1 on 2024-12-06 09:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_alter_productpurchase_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 11, 17, 37, 6003, tzinfo=datetime.timezone.utc)),
        ),
    ]
