# Generated by Django 5.1.1 on 2024-12-08 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_productpurchase_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 13, 24, 0, 404959, tzinfo=datetime.timezone.utc)),
        ),
    ]
