# Generated by Django 5.1.1 on 2024-12-08 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_alter_productpurchase_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 14, 18, 31, 828083, tzinfo=datetime.timezone.utc)),
        ),
    ]
