# Generated by Django 5.1.1 on 2024-12-08 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0013_alter_productpurchase_delivery_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='productpurchase',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 15, 0, 40, 543320, tzinfo=datetime.timezone.utc)),
        ),
    ]
