# Generated by Django 5.1.1 on 2024-12-08 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0015_alter_productpurchase_delivery_time_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='delivery_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 8, 17, 12, 59, 225380, tzinfo=datetime.timezone.utc)),
        ),
    ]
